version: "3"
services:
  #PHP-service
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: php:8.2-fpm
    container_name: php_store
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAG: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #NGINX-service
  webserver:
    image: nginx:alpine
    container_name: nginx_store
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL-service
  db:
    image: mysql:8.0.32
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "7706:3306"
    environment:
      MYSQL_DATABASE: obj_store
      MYSQL_USER: obj_store
      MYSQL_PASSWORD: obj_store
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql/
      - ./docker/mysql/conf/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "4446:80"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
